update precourse post: add schedule
fs-linguistics/fs-linguistics.github.io pull request #95
Opened 2024-09-24 16:14 UTC by smhancode

2024-09-24 16:29 UTC, ErikZeiner requested changes
Please fill in the time, remove the location from the table and put it as a separate chapter.
include 'schedule subject to change'
and make the please bring not a list, since there will be no more to bring

2024-09-24 20:15 UTC, smhancode commented
updated

2024-09-24 20:21 UTC, smhancode commented
again

2024-09-25 01:37 UTC, ErikZeiner approved these changes

2024-09-25 01:38 UTC, merged